Imports System.IO

Public Class Form1

    Dim currentURL As String 'URL / path of content being displayed at the time
    Dim counter1 As Integer = 0 'count of document number that is being displayed
    Dim counter2 As Integer = 0 'number of rotations through the entire presentation
    Dim fileCount As Integer = 1 'count of files in array that will be cycled through
    Dim dir As String = My.Application.Info.DirectoryPath 'get path where application is being launched from
    Dim currDir As New DirectoryInfo(dir)
    Private WithEvents webBrowser1 As WebBrowser


    Public Sub New()

        ' Create the form layout. If you are using Visual Studio, 
        ' you can replace this code with code generated by the designer. 
        InitializeForm()

        ' surpress any errors thrown by website.  not doing this has cause the application to crash due to dialogs being open while trying to navigate to next content
        webBrowser1.ScriptErrorsSuppressed = True
        ' Load the user's home page.
        webBrowser1.GoHome()

    End Sub
    ' Navigates to the URL in the address box when 
    ' the Go button is clicked.

    ' Navigates to the given URL if it is valid.
    Private Sub Navigate(ByVal address As String)
        Dim open As New OpenFileDialog

        'navigate to the content passed through


        If String.IsNullOrEmpty(address) Then Return
        If address.Equals("about:blank") Then Return
        If Not address.StartsWith("http://") And
            Not address.StartsWith("https://") Then
            address = "http://" & address
        End If
        Try
            webBrowser1.Navigate(New Uri(address))
        Catch ex As System.UriFormatException
            Return
        End Try

    End Sub



    Private Sub InitializeForm()

        'creates a web form that opens in full screen with no scrollbars or menus and hides cursor

        'webBrowser1 = New WebBrowser()
        webBrowser1 = New WebBrowser
        webBrowser1.Dock = DockStyle.Fill
        Me.Size = SystemInformation.PrimaryMonitorSize
        Me.WindowState = 2
        'Me.Location = Point(0, 0)
        Me.TopMost = True
        Me.FormBorderStyle = 0
        webBrowser1.ScrollBarsEnabled = False
        Controls.Add(webBrowser1)
        Cursor.Hide()
    End Sub

    <STAThread()>
    Public Shared Sub Main()
        'Application.EnableVisualStyles()
        'Application.Run(New Form1())
    End Sub

    Private Sub Form1_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        timer1 = New System.Windows.Forms.Timer()
        Timer1.Interval = 1 'wait 20 seconds per page
        Timer1.Start()
        'immediately go to the first piece of content

    End Sub

    Private Sub Timer1_Tick(sender As Object, e As EventArgs) Handles Timer1.Tick
        Timer1.Interval = 20000 'change timer to wait 20 seconds per page

        Dim listOfFiles As New ArrayList

        Dim fiArr As FileInfo() = currDir.GetFiles()


        'scan for files of various types and put into their own arrays
        Dim PDFs() As FileInfo = New IO.DirectoryInfo(dir).GetFiles("*.pdf", IO.SearchOption.AllDirectories)
        Dim URLs() As FileInfo = New IO.DirectoryInfo(dir).GetFiles("*.htm", IO.SearchOption.AllDirectories)
        Dim XLSXs() As FileInfo = New IO.DirectoryInfo(dir).GetFiles("*.xlsx", IO.SearchOption.AllDirectories)
        Dim XLSs() As FileInfo = New IO.DirectoryInfo(dir).GetFiles("*.xls", IO.SearchOption.AllDirectories)

        'compile all previous arrays into one "master" array
        For Each n In PDFs
            listOfFiles.Add(n)
        Next

        For Each m In URLs
            listOfFiles.Add(m)
        Next

        For Each m In XLSs
            listOfFiles.Add(m)
        Next

        For Each m In XLSXs
            listOfFiles.Add(m)
        Next

        'count number of objects in the listOfFiles array
        fileCount = listOfFiles.Count

        'if there are no files in the array, terminate the application and run the "logoff.bat" file
        If fileCount = 0 Then
            'System.Diagnostics.Process.Start(dir.ToString & "\logoff.bat")
            Me.Close()
        End If

        'determine the "link" in the array

        Try
            Dim link As String = IO.Path.Combine(dir, listOfFiles(counter1).FullName)
            'navigate to the link and incriment for the next counter
            webBrowser1.Navigate(link)
            counter1 += 1
            'If the counter is the end of the array, loop back to position 0 and incriment counter2
            If counter1 >= fileCount Then
                counter1 = 0
                counter2 += 1
            End If
            'if the presentation has looped 25 times, log off the session
            If counter2 = 25 Then
                'System.Diagnostics.Process.Start(dir.ToString & "\logoff.bat")
                Me.Close()
            End If
        Catch ex As Exception
            'System.Diagnostics.Process.Start(dir.ToString & "\logoff.bat")
            Me.Close()
        End Try

    End Sub

    Private Sub Form1_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles MyBase.KeyDown
        If e.KeyCode = Keys.Escape Then Me.Close()
    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub
End Class
